apiVersion: v1
entries:
  checkRTPAPI:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-03-13T10:00:30.026592+08:00"
    description: A Helm chart for Kubernetes
    digest: 7ff2779f14ed6bd3dbd3975781cf30415677bb91ab5ffe49d02091ac73d2c8d0
    name: checkRTPAPI
    type: application
    urls:
    - checkRTPAPI-0.1.0.tgz
    version: 0.1.0
generated: "2025-03-13T10:00:30.02618+08:00"
